name = "vestibule"
version = "0.1.0"
description = "A Gleam project"
licences = ["MIT"]
repository = { type = "github", user = "tylerbutler", repo = "vestibule" }
gleam = ">= 1.7.0"

# Uncomment to mark internal modules (not exported in public API):
# internal_modules = ["vestibule/internal", "vestibule/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.48.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
