name = "vestibule_microsoft"
version = "0.1.0"
description = "Microsoft OAuth strategy for vestibule"
licences = ["MIT"]
repository = { type = "github", user = "tylerbutler", repo = "vestibule", path = "packages/vestibule_microsoft" }
gleam = ">= 1.7.0"

[dependencies]
vestibule = { path = "../.." }
gleam_stdlib = ">= 0.48.0 and < 2.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
glow_auth = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.8.0 and < 1.0.0"
